### PR TITLE
Add nice html formatting for invitation emails

### PR DESCRIPTION
**Pull request by cweems**
Simple email template from
https://github.com/leemunroe/responsive-html-email-template

screen shot 2017-07-18 at 6 31 04 pm

### CODE REVIEW

**Comment by tmaybe** [comment]
Is "or copy" in the email text still relevant? I guess they could right-click on the button and copy the link that way...

**Comment by alsomanya** [comment]
Agree with @tmaybe on that copy weirdness, but not blocking. LGTM. 

Sidenote, would responding to this email go to our team? Is there an alias the email comes from, or is it a no-reply?

**Comment by tmaybe** [comment]
It's a no reply at the moment but we could wire it up so responses go to the team.

**Comment by disambiguator** [comment]
changed

**Pull request merged**
