### PR TITLE
Add validation errors for clients/new and add uniqueness for phone numbers

### LINKED ISSUE #77: Editing a client changes date of last contact
Changing a client's name or phone number should not change their position on the "last contacted" list. Only sending texts should count as contact.

### PR DESCRIPTION
**Pull request by disambiguator**
Resolves #77

https://waffle.io/codeforamerica/clientcomm-project/cards/595d241f49355c008011411b

 - Add error handling for clients/new page to prevent 500 errors
 - Consolidate controller level tests

### CODE REVIEW

**Comment by disambiguator** [comment]
@alsomanya 

Right now this is what it looks like. I don't know an email address to use so I just put the chat message.
screen shot 2017-07-05 at 9 03 34 pm

**Comment by tmaybe** [comment]
Looks good to me. When @alsomanya signs off on the UX I'll merge.

**Comment by alsomanya** [comment]
Let's change the error text to:
Phone number is already in use. If you need help, you can click the chat button at the bottom of your screen.

After that, LGTM.

**Comment by tmaybe** [comment]
Closes #77

**Pull request merged**
